### ISSUE TITLE
trying to get this to work with a stm32f0 chip

### ISSUE THREAD

**Issue by W-M-D** [boltrobotics/cmake-helpers#1]
however, it seems no matter how I set the STM32_CHIP it reverts to F1

**Comment by svkapustin** [comment]
Hey Matthew,
I changed the build a bit. It can get to compilation for other chip. The example code doesn't compile for a random chip I tried (stm32f0030x6), but it's a different issue now.
Give it a try for your code.
Cheers

**Comment by W-M-D** [comment]
Wow, thank you very much!

**Comment by W-M-D** [comment]
The reason it doesn't compile is the libopencm build somehow keeps on setting f1 in the stm build dir. I don't know how but if you change it manually after generation it compiles.

**Comment by svkapustin** [comment]
No further input. Closing.
