### ISSUE TITLE
CCPCHECK cant find any of the includes.

### ISSUE THREAD

**Issue by W-M-D** [boltrobotics/cmake-helpers#2]
hello, do you have any idea how to configure ccpcheck to find the includes?

**Comment by svkapustin** [comment]
If you ask how to set up your custom project's ccpcheck dependency then look into init.cmake and function setup_dep. 
See if you can use it as a template and create your own.

For example, in one of my projects I call the function like this:
setup_dep(boltalog $ENV{BOLTALOG_HOME} SUB_DIR "src/${BOARD_FAMILY}")
