### ISSUE TITLE
uttlerly broken with any compiler past arm-none-eabi-gcc 7.3.1 

### ISSUE THREAD

**Issue by W-M-D** [boltrobotics/cmake-helpers#3]
any compiler past arm-none-eabi-gcc (15:7-2018-q2-6) 7.3.1 20180622 (release) and or cmake version 3.13.4 breaks this project completely. As of yet I'm unsure why. It seems to be a C++ linker issue or something. It will either not compile because of a room overflow or not boot.

**Comment by kapucin** [comment]
There is an opportunity for you to figure it out and make a proposal for the fix.

**Comment by W-M-D** [comment]
okay i think i got part of it -specs=nosys.specs is now --specs=nosys.specs . However -specs=nosys.specs doesn't generate a linker error.

**Comment by W-M-D** [comment]
nevermind i didn't erase before flashing

**Comment by W-M-D** [comment]
wait don't close it. I meant that something is wrong with the linking. Therefore if you flash a new bin over the old one it still runs

**Comment by W-M-D** [comment]
So far I haven't made that much progress. I'm able to run a basic program but anything past that seems to break. It seems as if the compiler and or linker is optimizing out function returns on void functions. So it gets to a handler of a class and then hangs there in a loop. Something with the older version of binutils or ld links the functions correctly. I'm guessing it has something to do with whatever generates the "Scanning dependencies of target " message that's no longer showing up. Luckily I was smart enough to make a vagrant build as a builder a year ago. But I really want to fix this for the newer toolchain.

**Comment by W-M-D** [comment]
Okay, it turns out it was an issue with newlib. After changing my void functions to return something and adding --specs=nano.specs to the compiler options everything works.

**Comment by kapucin** [comment]
Great. Thanks for the update.
